services:
  - type: web
    name: portfolio-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false
    nodeVersion: 18.x
    packageManager: npm
    healthCheckPath: /
    autoDeploy: true
